Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-b70554c8
      AvailabilityZone: us-east-1a
      InstanceType: t2.micro
      Tags:
        - 
          Key: Type
          Value: WebServer
        -
          Key: Name
          Value: Udemy
        -
          Key: Department
          Value: Finance

